# Generated by Django 3.2.4 on 2021-07-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('group_year', models.DateField(auto_now_add=True, verbose_name='Yaratilgan sanai')),
                ('slug', models.SlugField(max_length=100, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_mentor', models.CharField(max_length=50, verbose_name='Guruh Mentori')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=100, verbose_name='Familiysai')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telfon raqami')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Yashash manzili')),
                ('pay', models.BooleanField(default=False, verbose_name="To'lovi")),
                ('slug', models.SlugField(max_length=100, verbose_name='*')),
                ('class_mentors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mentors')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='main.groups')),
            ],
        ),
    ]
