# Generated by Django 3.2.4 on 2021-07-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_mentors',
        ),
    ]
