# Generated by Django 3.2.4 on 2021-07-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_class_mentors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
