# Generated by Django 3.2.4 on 2021-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Weekdays',
            field=models.ManyToManyField(to='main.Weekday'),
        ),
    ]
