# Generated by Django 3.2.4 on 2021-07-03 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_weekdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Weekdays',
        ),
        migrations.AddField(
            model_name='student',
            name='course_times',
            field=models.CharField(choices=[('key', '09:00 dan 11:00 gacha'), ('key', '13:00 dan 15:00 gacha'), ('key', '15:00 dan 17:00 gacha'), ('key', '17:00 dan 18:00 gacha')], default=datetime.datetime(2021, 7, 3, 11, 0, 17, 445734, tzinfo=utc), max_length=200, verbose_name='Dars vaqtlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='weekday',
            field=models.CharField(choices=[('key', 'Dush-Chor-Juma'), ('key', 'Sesh-Pay-Shan')], default=datetime.datetime(2021, 7, 3, 11, 0, 32, 565441, tzinfo=utc), max_length=200, verbose_name='Hafta kunlari'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
