# Generated by Django 3.2.4 on 2021-07-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210703_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='course_times',
            field=models.CharField(choices=[('09:00 dan 11:00 gacha', '09:00 dan 11:00 gacha'), ('13:00 dan 15:00 gacha', '13:00 dan 15:00 gacha'), ('15:00 dan 17:00 gacha', '15:00 dan 17:00 gacha'), ('17:00 dan 18:00 gacha', '17:00 dan 18:00 gacha')], max_length=200, verbose_name='Dars vaqtlari'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='weekday',
            field=models.CharField(choices=[('Dush-Chor-Juma', 'Dush-Chor-Juma'), ('Sesh-Pay-Shan', 'Sesh-Pay-Shan')], max_length=200, verbose_name='Hafta kunlari'),
        ),
    ]
